name: Deploy NestJS to Server

on:
  push:
    branches:
      - main  # 监听 main 分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 替换为你的 Node 版本

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build NestJS
        run: npm run build

      - name: Create remote directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /www/workspace/yishe-nest
            chmod 755 /www/workspace/yishe-nest

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist,package.json,package-lock.json"
          target: /www/workspace/yishe-nest
          strip_components: 0
          overwrite: true
          debug: true

      - name: SSH into server and restart with PM2
        id: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /www/workspace/yishe-nest
            rm -rf node_modules
            npm install --production --legacy-peer-deps
            if [ ! -d "node_modules" ]; then
              echo "::error::node_modules 目录创建失败"
              exit 1
            fi
            pm2 delete yishe-nest || true
            pm2 start dist/main.js --name yishe-nest
            sleep 5
            if ! pm2 list | grep -q "yishe-nest.*online"; then
              echo "::error::服务启动失败"
              exit 1
            fi

      - name: Send Feishu Notification
        if: steps.deploy.outcome == 'success'
        run: |
          curl -X POST ${{ secrets.FEISHU_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "msg_type": "text",
              "content": {
                "text": "✅ NestJS 项目部署成功！🎉\n分支: main\n时间: '"$(date +'%Y-%m-%d %H:%M:%S')"'"
              }
            }'

      - name: Send Failure Notification
        if: steps.deploy.outcome == 'failure'
        run: |
          curl -X POST ${{ secrets.FEISHU_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "msg_type": "text",
              "content": {
                "text": "❌ NestJS 项目部署失败！\n分支: main\n时间: '"$(date +'%Y-%m-%d %H:%M:%S')"'"
              }
            }'

